# Dockerfile (в корне проекта)
FROM python:3.10-slim

WORKDIR /app

# Скопировать и установить только prod-зависимости
COPY prod-requirements.txt .
RUN pip install --no-cache-dir -r prod-requirements.txt

# Скопировать весь проект
COPY . .

# Открыть порт
EXPOSE 8000

# Команда запуска
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
